openapi: 3.0.1
info:
  title: LoccanaMasterItemQtys
  description: API Definition of LoccanaMasterItemQtys
  version: 1.0.0
servers:
- url: http://localhost:8290/loccana/master/item_qty
paths:
  /{id}:
    get:
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
