openapi: 3.0.1
info:
  title: LoccanaMasterItemTypes
  description: API Definition of LoccanaMasterItemTypes
  version: 1.0.0
servers:
- url: http://localhost:8290/loccana/master/item_types
paths:
  /:
    get:
      responses:
        default:
          description: Default response
